management:
  server:
    port: 8090
  endpoints:
    enabled-by-default: false
    web:
      base-path: "/"
      exposure:
        include: health, metrics, prometheus
  endpoint:
    health:
      probes:
        enabled: true
      enabled: true
      show-components: "always"
    metrics.enabled: true
    prometheus.enabled: true
  health:
    diskspace.enabled: false